### ISSUE TITLE
Load names from CSVs if present

### ISSUE THREAD

**Issue by spalladino** [instedd/location_service#3]
GADM provides a CSV with location names along with the shapefiles. These files contain the correct location name, as the shapefile format does not support unicode characters. 

When importing a shapefile, check if a file with the same name but extension CSV exists, and use it to load the location names.

**Comment by nditada** [comment]
![screen shot 2015-05-28 at 11 35 23 am](https://cloud.githubusercontent.com/assets/1359189/7862719/1508e628-052e-11e5-9c50-b604680b35f9.png)
