### ISSUE TITLE
Question on Location Service

### ISSUE THREAD

**Issue by steesdale** [instedd/location_service#4]
Will there be a UI to manage the data/shapefiles?  Or just a database?   

Is there a linkage here for the facility registry work we do or RM at large? 

@edjez @nditada

**Comment by spalladino** [comment]
There is no UI currently on the project, all data is imported via command-line scripts. As for facility registry, I'll defer to Ed or Nico.

**Comment by nditada** [comment]
No, totally unrelated to RM for now.
